//
//Copyright (c) 2025 Tobias Schäfer. All rights reserved.
//Licensed under the MIT license, see LICENSE in the project root for details.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterAgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Tags           []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	LogSources     []string               `protobuf:"bytes,3,rep,name=log_sources,json=logSources,proto3" json:"log_sources,omitempty"`
	Metrics        bool                   `protobuf:"varint,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	MetricsTargets []string               `protobuf:"bytes,5,rep,name=metrics_targets,json=metricsTargets,proto3" json:"metrics_targets,omitempty"`
	Profiles       bool                   `protobuf:"varint,6,opt,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_internal_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterAgentRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegisterAgentRequest) GetLogSources() []string {
	if x != nil {
		return x.LogSources
	}
	return nil
}

func (x *RegisterAgentRequest) GetMetrics() bool {
	if x != nil {
		return x.Metrics
	}
	return false
}

func (x *RegisterAgentRequest) GetMetricsTargets() []string {
	if x != nil {
		return x.MetricsTargets
	}
	return nil
}

func (x *RegisterAgentRequest) GetProfiles() bool {
	if x != nil {
		return x.Profiles
	}
	return false
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_internal_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentResponse) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type DeregisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterAgentRequest) Reset() {
	*x = DeregisterAgentRequest{}
	mi := &file_internal_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterAgentRequest) ProtoMessage() {}

func (x *DeregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*DeregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterAgentRequest) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type DeregisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterAgentResponse) Reset() {
	*x = DeregisterAgentResponse{}
	mi := &file_internal_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterAgentResponse) ProtoMessage() {}

func (x *DeregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*DeregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{3}
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_internal_api_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentRequest) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type GetAgentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResourceId     string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Tags           []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	LogSources     []string               `protobuf:"bytes,4,rep,name=log_sources,json=logSources,proto3" json:"log_sources,omitempty"`
	Metrics        bool                   `protobuf:"varint,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	MetricsTargets []string               `protobuf:"bytes,6,rep,name=metrics_targets,json=metricsTargets,proto3" json:"metrics_targets,omitempty"`
	Profiles       bool                   `protobuf:"varint,7,opt,name=profiles,proto3" json:"profiles,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_internal_api_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetAgentResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetAgentResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetAgentResponse) GetLogSources() []string {
	if x != nil {
		return x.LogSources
	}
	return nil
}

func (x *GetAgentResponse) GetMetrics() bool {
	if x != nil {
		return x.Metrics
	}
	return false
}

func (x *GetAgentResponse) GetMetricsTargets() []string {
	if x != nil {
		return x.MetricsTargets
	}
	return nil
}

func (x *GetAgentResponse) GetProfiles() bool {
	if x != nil {
		return x.Profiles
	}
	return false
}

func (x *GetAgentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_internal_api_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{6}
}

type AgentListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentListItem) Reset() {
	*x = AgentListItem{}
	mi := &file_internal_api_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentListItem) ProtoMessage() {}

func (x *AgentListItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentListItem.ProtoReflect.Descriptor instead.
func (*AgentListItem) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{7}
}

func (x *AgentListItem) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *AgentListItem) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentListItem       `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_internal_api_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListAgentsResponse) GetAgents() []*AgentListItem {
	if x != nil {
		return x.Agents
	}
	return nil
}

type GetAgentConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentConfigRequest) Reset() {
	*x = GetAgentConfigRequest{}
	mi := &file_internal_api_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentConfigRequest) ProtoMessage() {}

func (x *GetAgentConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentConfigRequest.ProtoReflect.Descriptor instead.
func (*GetAgentConfigRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetAgentConfigRequest) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type GetAgentConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentConfigResponse) Reset() {
	*x = GetAgentConfigResponse{}
	mi := &file_internal_api_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentConfigResponse) ProtoMessage() {}

func (x *GetAgentConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentConfigResponse.ProtoReflect.Descriptor instead.
func (*GetAgentConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetAgentConfigResponse) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetServiceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceInfoRequest) Reset() {
	*x = GetServiceInfoRequest{}
	mi := &file_internal_api_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceInfoRequest) ProtoMessage() {}

func (x *GetServiceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServiceInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{11}
}

type GetServiceInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Release       string                 `protobuf:"bytes,4,opt,name=release,proto3" json:"release,omitempty"`
	Commit        string                 `protobuf:"bytes,5,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceInfoResponse) Reset() {
	*x = GetServiceInfoResponse{}
	mi := &file_internal_api_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceInfoResponse) ProtoMessage() {}

func (x *GetServiceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServiceInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_api_proto_rawDescGZIP(), []int{12}
}

func (x *GetServiceInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetServiceInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetServiceInfoResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetServiceInfoResponse) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *GetServiceInfoResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

var File_internal_api_api_proto protoreflect.FileDescriptor

const file_internal_api_api_proto_rawDesc = "" +
	"\n" +
	"\x16internal/api/api.proto\x12\x05finch\"\xc6\x01\n" +
	"\x14RegisterAgentRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x1f\n" +
	"\vlog_sources\x18\x03 \x03(\tR\n" +
	"logSources\x12\x18\n" +
	"\ametrics\x18\x04 \x01(\bR\ametrics\x12'\n" +
	"\x0fmetrics_targets\x18\x05 \x03(\tR\x0emetricsTargets\x12\x1a\n" +
	"\bprofiles\x18\x06 \x01(\bR\bprofiles\")\n" +
	"\x15RegisterAgentResponse\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\tR\x03rid\"*\n" +
	"\x16DeregisterAgentRequest\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\tR\x03rid\"\x19\n" +
	"\x17DeregisterAgentResponse\"#\n" +
	"\x0fGetAgentRequest\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\tR\x03rid\"\x82\x02\n" +
	"\x10GetAgentResponse\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1f\n" +
	"\vlog_sources\x18\x04 \x03(\tR\n" +
	"logSources\x12\x18\n" +
	"\ametrics\x18\x05 \x01(\bR\ametrics\x12'\n" +
	"\x0fmetrics_targets\x18\x06 \x03(\tR\x0emetricsTargets\x12\x1a\n" +
	"\bprofiles\x18\a \x01(\bR\bprofiles\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\x13\n" +
	"\x11ListAgentsRequest\"=\n" +
	"\rAgentListItem\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\tR\x03rid\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"B\n" +
	"\x12ListAgentsResponse\x12,\n" +
	"\x06agents\x18\x01 \x03(\v2\x14.finch.AgentListItemR\x06agents\")\n" +
	"\x15GetAgentConfigRequest\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\tR\x03rid\"0\n" +
	"\x16GetAgentConfigResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\"\x17\n" +
	"\x15GetServiceInfoRequest\"\x95\x01\n" +
	"\x16GetServiceInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x18\n" +
	"\arelease\x18\x04 \x01(\tR\arelease\x12\x16\n" +
	"\x06commit\x18\x05 \x01(\tR\x06commit2\xfb\x02\n" +
	"\fAgentService\x12J\n" +
	"\rRegisterAgent\x12\x1b.finch.RegisterAgentRequest\x1a\x1c.finch.RegisterAgentResponse\x12P\n" +
	"\x0fDeregisterAgent\x12\x1d.finch.DeregisterAgentRequest\x1a\x1e.finch.DeregisterAgentResponse\x12;\n" +
	"\bGetAgent\x12\x16.finch.GetAgentRequest\x1a\x17.finch.GetAgentResponse\x12A\n" +
	"\n" +
	"ListAgents\x12\x18.finch.ListAgentsRequest\x1a\x19.finch.ListAgentsResponse\x12M\n" +
	"\x0eGetAgentConfig\x12\x1c.finch.GetAgentConfigRequest\x1a\x1d.finch.GetAgentConfigResponse2\\\n" +
	"\vInfoService\x12M\n" +
	"\x0eGetServiceInfo\x12\x1c.finch.GetServiceInfoRequest\x1a\x1d.finch.GetServiceInfoResponseB$Z\"github.com/tschaefer/finch/api;apib\x06proto3"

var (
	file_internal_api_api_proto_rawDescOnce sync.Once
	file_internal_api_api_proto_rawDescData []byte
)

func file_internal_api_api_proto_rawDescGZIP() []byte {
	file_internal_api_api_proto_rawDescOnce.Do(func() {
		file_internal_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_api_proto_rawDesc), len(file_internal_api_api_proto_rawDesc)))
	})
	return file_internal_api_api_proto_rawDescData
}

var file_internal_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_api_api_proto_goTypes = []any{
	(*RegisterAgentRequest)(nil),    // 0: finch.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),   // 1: finch.RegisterAgentResponse
	(*DeregisterAgentRequest)(nil),  // 2: finch.DeregisterAgentRequest
	(*DeregisterAgentResponse)(nil), // 3: finch.DeregisterAgentResponse
	(*GetAgentRequest)(nil),         // 4: finch.GetAgentRequest
	(*GetAgentResponse)(nil),        // 5: finch.GetAgentResponse
	(*ListAgentsRequest)(nil),       // 6: finch.ListAgentsRequest
	(*AgentListItem)(nil),           // 7: finch.AgentListItem
	(*ListAgentsResponse)(nil),      // 8: finch.ListAgentsResponse
	(*GetAgentConfigRequest)(nil),   // 9: finch.GetAgentConfigRequest
	(*GetAgentConfigResponse)(nil),  // 10: finch.GetAgentConfigResponse
	(*GetServiceInfoRequest)(nil),   // 11: finch.GetServiceInfoRequest
	(*GetServiceInfoResponse)(nil),  // 12: finch.GetServiceInfoResponse
}
var file_internal_api_api_proto_depIdxs = []int32{
	7,  // 0: finch.ListAgentsResponse.agents:type_name -> finch.AgentListItem
	0,  // 1: finch.AgentService.RegisterAgent:input_type -> finch.RegisterAgentRequest
	2,  // 2: finch.AgentService.DeregisterAgent:input_type -> finch.DeregisterAgentRequest
	4,  // 3: finch.AgentService.GetAgent:input_type -> finch.GetAgentRequest
	6,  // 4: finch.AgentService.ListAgents:input_type -> finch.ListAgentsRequest
	9,  // 5: finch.AgentService.GetAgentConfig:input_type -> finch.GetAgentConfigRequest
	11, // 6: finch.InfoService.GetServiceInfo:input_type -> finch.GetServiceInfoRequest
	1,  // 7: finch.AgentService.RegisterAgent:output_type -> finch.RegisterAgentResponse
	3,  // 8: finch.AgentService.DeregisterAgent:output_type -> finch.DeregisterAgentResponse
	5,  // 9: finch.AgentService.GetAgent:output_type -> finch.GetAgentResponse
	8,  // 10: finch.AgentService.ListAgents:output_type -> finch.ListAgentsResponse
	10, // 11: finch.AgentService.GetAgentConfig:output_type -> finch.GetAgentConfigResponse
	12, // 12: finch.InfoService.GetServiceInfo:output_type -> finch.GetServiceInfoResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_api_proto_init() }
func file_internal_api_api_proto_init() {
	if File_internal_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_api_proto_rawDesc), len(file_internal_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_api_api_proto_goTypes,
		DependencyIndexes: file_internal_api_api_proto_depIdxs,
		MessageInfos:      file_internal_api_api_proto_msgTypes,
	}.Build()
	File_internal_api_api_proto = out.File
	file_internal_api_api_proto_goTypes = nil
	file_internal_api_api_proto_depIdxs = nil
}
